server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234


  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  logging:
    level:
      org:
        springframework:
          security=DEBUG:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 362299744188-ghpnvkvvp4b5841ii1il78r5thna240t.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
